version: '3'
services:
    # Mongo image
    mongodb:
        image: 'mongo'
        container_name: 'mongodb'
        volumes:
            - mongodata:/data/db
        restart: always
        ports:
            - '20717:20717'

    # Nginx
    nginx:
        depends_on:
            - api
            - client
        restart: always
        build:
            dockerfile: Dockerfile.dev
            context: ./nginx
        ports:
            - '3050:80'
    # Server build, volumes, .env
    api:
        depends_on:
            - mongodb
        build:
            dockerfile: Dockerfile.dev
            context: ./server
        volumes:
            - /app/node_modules
            - ./server:/app
        environment:
            - MGHOST=mongodb
            - MGDATABASE=jubo
        links:
            - mongodb

    client:
        depends_on:
            - api
        stdin_open: true
        build:
            dockerfile: Dockerfile.dev
            context: ./client
        volumes:
            - /app/node_modules
            - ./client:/app

volumes:
    mongodata:
